blogger_finance:
    resource: "@BloggerFinanceBundle/Controller/"
    type:     annotation
    prefix:   /finance

blogger_movie:
    resource: "@BloggerMovieBundle/Controller/"
    type:     annotation
    prefix:   /movie

blogger_user:
    resource: "@BloggerUserBundle/Controller/"
    type:     annotation
    prefix:   /profile

blogger_admin:
    resource: "@BloggerAdminBundle/Controller/"
    type:     annotation
    prefix:   /admin

blogger_blog:
    resource: "@BloggerBlogBundle/Resources/config/routing.yml"
    prefix:   /

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"